databaseType = "MySql"
name = "OFIS"
id = "4cf34941-be49-41da-baab-14355c49fdb2"

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
schemaModel = "./schema-model"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[flyway]
mixed = true
outOfOrder = true
locations = [ "filesystem:migrations" ]
validateMigrationNaming = true

[environments.development]
url = "jdbc:mysql://localhost:3306"
schemas = [ "ofis" ]
displayName = "ofis"
